name: "❓ 问题反馈"
description: "请认真填写本模板中的各项内容。您的反馈对项目改进至关重要，感谢您的支持！"
title: "[Question]: "
labels:
  - question
  - high
type: Question
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您为本项目贡献力量！

        为帮助我们更高效地理解您的问题，请尽可能详细、准确地填写以下内容。

        - 提交前请查阅 [CONTRIBUTING](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/zh-CN/CONTRIBUTING.md) 以了解贡献流程和要求。
        - 请遵守我们的 [行为准则](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/zh-CN/CODE_OF_CONDUCT.md)，保持尊重与友善。
        - 提交前请先搜索现有 Issue，避免重复反馈。

        感谢您的理解与配合！🙏

  - type: markdown
    attributes:
      value: |
        ### 关于 ❓ 问题反馈

        本模板专用于反馈使用过程中遇到的疑惑、理解障碍或需进一步说明的问题。

        若您的问题属于 [🐛 Bug 反馈](https://github.com/ArcesTeam/{{project-name}}/issues/new?template=01_Bug_Report.yaml)、[🚀 性能反馈](https://github.com/ArcesTeam/{{project-name}}/issues/new?template=02_Performance_Report.yaml)、[🛠️ 功能增强反馈](https://github.com/ArcesTeam/{{project-name}}/issues/new?template=04_Enhancement_Report.yaml) 或 [✨ 新增功能反馈](https://github.com/ArcesTeam/{{project-name}}/issues/new?template=05_Feature_Report.yaml)，请使用相应模板。

        > 如需了解与本项目无关的其他问题（如团队相关），可访问 [Discussions](https://github.com/orgs/ArcesTeam/discussions) 进一步探讨。

        再次感谢您的支持！🙏

        ---

  - type: textarea
    id: question-description
    attributes:
      label: "问题描述"
      description: "请详细描述您遇到的疑惑或需解答的问题。"
      placeholder: "请详细说明您的问题或疑问。"
    validations:
      required: true

  - type: textarea
    id: expected-answer
    attributes:
      label: "期望的解答或帮助（可选）"
      description: "您希望由谁解答？希望获得何种帮助？"
      placeholder: "请描述您的期望。"
    validations:
      required: false

  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息（可选）"
      description: |
        如有相关代码、日志或其他信息，请填写于此，便于我们理解问题。
        您也可上传附件以补充说明。
    validations:
      required: false

  - type: input
    id: contact-details
    attributes:
      label: "联系方式（可选）"
      description: "如需进一步沟通，我们可通过哪些方式联系您？"
      placeholder: "如：email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        提交 Issue 后，您可继续通过评论上传截图或其他附件（如 xx.log）。

  - type: markdown
    attributes:
      value: |
        ---

        ### 行为准则声明

        提交本 Issue 即表示您同意遵守我们的[行为准则](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/zh-CN/CODE_OF_CONDUCT.md)。
        感谢您保持友善与尊重！

        ✅ 我同意遵守本项目的行为准则。

        ---

