name: "📚️ Documentation Report"
description: "Please fill out all sections of this template carefully. Your feedback is crucial for improving the project. Thank you for your support!"
title: "[Doc]: "
labels:
  - documentation
  - low
type: Documentation
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to this project!

        To help us process your feedback more efficiently, please fill out the following sections as thoroughly and accurately as possible.

        - Before submitting, please review the [CONTRIBUTING](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING.md) guidelines to understand the contribution process and requirements.
        - Please follow our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md) and remain respectful and friendly.
        - Search existing issues before submitting to avoid duplicates.

        Thank you for your understanding and cooperation! 🙏

  - type: markdown
    attributes:
      value: |
        ### About 📚️ Documentation Reports

        This template is dedicated to reporting issues related to documentation, comments, API docs, WIKI, etc.

        For language file issues (such as translation or text specification), please visit the i18n section of [Discussions](https://github.com/orgs/ArcesTeam/discussions) for further discussion.

        Thank you again for your support! 🙏

        ---

  - type: checkboxes
    id: doc-type
    attributes:
      label: "Scope Involved"
      description: "Please select the type(s) of documentation to be adjusted."
      options:
        - label: "Language Files"
        - label: "Code Comments"
        - label: "API Documentation"
        - label: "Project Documentation"
        - label: "WIKI"

  - type: textarea
    id: detailed-description
    attributes:
      label: "Issue Description"
      description: "Please describe in detail the text to be corrected and the reason."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    id: relevant-log-output
    attributes:
      label: "Relevant Text/Code (Optional)"
      description: "Please paste the text, code, or other information related to the documentation issue. Content will be automatically formatted."
      render: shell
    validations:
      required: false

  - type: input
    id: contact-details
    attributes:
      label: "Contact Information (Optional)"
      description: "If further communication is needed, how can we contact you?"
      placeholder: "e.g., email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        After submitting the issue, you may continue to upload screenshots or other attachments (such as xx.log) via comments.

  - type: markdown
    attributes:
      value: |
        ---

        ### Code of Conduct Statement

        By submitting this issue, you agree to abide by our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md).
        Thank you for being friendly and respectful!

        ✅ I agree to abide by the project's Code of Conduct.

        ---


