name: "🧩 Other Report"
description: "Please fill out all sections of this template carefully. Your feedback is crucial for improving the project. Thank you for your support!"
title: "[Other]: "
labels:
  - other
  - low
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to this project!

        To help us process your feedback more efficiently, please fill out the following sections as thoroughly and accurately as possible.

        - Before submitting, please review the [CONTRIBUTING](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING.md) guidelines to understand the contribution process and requirements.
        - Please follow our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md) and remain respectful and friendly.
        - Search existing issues before submitting to avoid duplicates.

        Thank you for your understanding and cooperation! 🙏

  - type: markdown
    attributes:
      value: |
        ### About 🧩 Other Reports

        This template is for any feedback not covered by the above templates. If you are unsure which template to use, please use this one.

        You may submit feedback about project experience, suggestions, opinions, or support, advice, and comments for the development team. As long as the content complies with the [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md), you may use this template.

        Unless otherwise required, we recommend using [Discussions](https://github.com/orgs/ArcesTeam/discussions) for further discussion, which helps centralize feedback.

        Thank you again for your support! 🙏

        ---

  - type: textarea
    id: detailed-description
    attributes:
      label: "Feedback Content"
      description: "Please describe your feedback and reasons in detail."
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: input
    id: contact-details
    attributes:
      label: "Contact Information (Optional)"
      description: "If further communication is needed, how can we contact you?"
      placeholder: "e.g., email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        After submitting the issue, you may continue to upload screenshots or other attachments (such as xx.log) via comments.

  - type: markdown
    attributes:
      value: |
        ---

        ### Code of Conduct Statement

        By submitting this issue, you agree to abide by our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md).
        Thank you for being friendly and respectful!

        ✅ I agree to abide by the project's Code of Conduct.

        ---


