name: "🧪 Dev Report"
description: "This template is for internal project developers only. Non-developers, please do not use it. Thank you for your understanding and cooperation!"
title: "[Dev]: "
labels:
  - development
  - low
type: Dev
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to this project!

        To help us process your feedback more efficiently, please fill out the following sections as thoroughly and accurately as possible.

        - Before submitting, please review the [CONTRIBUTING](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING.md) guidelines to understand the contribution process and requirements.
        - Please follow our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md) and remain respectful and friendly.
        - Search existing issues before submitting to avoid duplicates.

        Thank you for your understanding and cooperation! 🙏

  - type: markdown
    attributes:
      value: |
        ### About 🧪 Dev Reports

        This template is for internal project developers only, suitable for issues related to design and development processes, development documentation, build scripts, CI/CD, etc.

        It is recommended to refer to the Development section of the [CONTRIBUTING](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING.md) document, or check [CONTRIBUTING-DEV](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING-DEV.md) and [CONTRIBUTING-GUIDE](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CONTRIBUTING-GUIDE.md).

        Thank you again for your support! 🙏

        ---

  - type: input
    attributes:
      label: "Main Function Brief"
      description: "Please briefly describe the main function or development content of this module."
      placeholder: "e.g., Responsible for user authentication module development."
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Is it a sub-module?"
      description: "Is this issue a split from an existing issue? If yes, please add the relevant link for tracking."
      options:
        - "Yes (sub-module)"
        - "No (independent module)"
      default: 1
    validations:
      required: true

  - type: dropdown
    attributes:
      label: "Development Stage"
      description: "Please select the current development stage (for reference only)."
      options:
        - "Requirement Analysis"
        - "Design Stage"
        - "Coding Implementation"
        - "Testing Stage"
        - "Deployment"
        - "Maintenance"
      default: 2
    validations:
      required: false

  - type: textarea
    id: detailed-description
    attributes:
      label: "Module Development Steps Description"
      description: |
        Please describe in detail the design ideas, planned steps, and content involved in the development process. Standardized development logs help the long-term healthy development of the project.

        It is strongly recommended to create a dedicated issue for each code submission for binding, which is convenient for subsequent tracking and version recording.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: false

  - type: input
    id: contact-details
    attributes:
      label: "Contact Information (Optional)"
      description: "If further communication is needed, how can we contact you?"
      placeholder: "e.g., email@example.com"
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        After submitting the issue, you may continue to upload screenshots or other attachments (such as xx.log) via comments.

        Discussions, research, design changes, etc. during the development process can also be recorded and communicated in this issue.

        You may also upload relevant code, design documents, test cases, etc. as development records to share with the team.

  - type: markdown
    attributes:
      value: |
        ---

        ### Code of Conduct Statement

        By submitting this issue, you agree to abide by our [Code of Conduct](https://github.com/ArcesTeam/{{project-name}}/blob/main/.github/lang/en-US/CODE_OF_CONDUCT.md).
        Thank you for being friendly and respectful!

        ✅ I agree to abide by the project's Code of Conduct.

        ---


